alias: Drucker Beleuchtung ausschalten
description: Schaltet Druckerbeleuchtung aus, wenn beide Drucker aus sind
triggers:
  - entity_id:
      - switch.drucker_x1c
      - switch.drucker_p1s
    to: "off"
    trigger: state
conditions:
  - condition: state
    entity_id: switch.drucker_x1c
    state: "off"
  - condition: state
    entity_id: switch.drucker_p1s
    state: "off"
actions:
  - target:
      entity_id: switch.drucker_usb_licht
    action: switch.turn_off
    data: {}
mode: single