alias: P1S abschalten
description: "Turn off printer after 10min in idle/finish/failed and nozzletemp under 50.1"
triggers:
  - minutes: /1
    trigger: time_pattern
conditions:
  - condition: state
    entity_id: switch.drucker_p1s
    state: "on"
  - condition: template
    value_template: >
      {% set s = states('sensor.p1s_druckstatus') %} {{ s in
      ['idle', 'finish', 'failed'] and
         (now() - states.sensor.p1s_druckstatus.last_changed).total_seconds() > 600 }}
  - condition: template
    value_template: >
      {{ states('sensor.p1s_temperatur_der_duse') not in
      ['unknown', 'unavailable'] }}
  - condition: numeric_state
    entity_id: sensor.p1s_temperatur_der_duse
    below: 50.1
actions:
  - target:
      entity_id: switch.drucker_p1s
    action: switch.turn_off
    data: {}
  - data:
      message: P1S wurde automatisch abgeschaltet (idle/finish/failed + Düse ≤ 50 °C)
      level: warning
    action: system_log.write
mode: single